baseURL = '/'
languageCode = 'en-us'
title = 'The Chandler Zone'
theme = "kaslaanka"

[params]
  # color style
  color = 'linen'                 # linen, wheat, gray, light
  sitename = "Chandler Barlow Blog"
  copyrights = "Chandler Barlow"
  defaultList = "global"
  paginationLen = 5
  brief_about = "<center>This is just your standard dev blog.</center>"
  # header social icons
  twitter = 'ChanChanCanDo'     # twitter.com/YOUR_TWITTER_ID
  github = 'chandler-barlow'       # github.com/YOUR_GITHUB_ID
  instagram = 'mistablu' # instagram.com/YOUR_INSTAGRAM_ID
  rss = true                      # show rss icon with link

  # home page profile
  avatar = 'chandlerbrlw@gmail.com'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
  name = 'Chandler Barlow'
  bio = 'Im a full stack developer based in dallas.'

  # misc
  monoDarkIcon = true             # show monochrome dark mode icon
